### ISSUE TITLE
[dnstap logger] Atoi error with dnstap logger

### ISSUE THREAD

**Issue by mikeS7** [dmachard/go-dns-collector#110]
Got error with dnstap logger enabled:

`ERROR: 2022/09/04 09:08:13.989261 logger dnstap sender - error to encode dnstap response port strconv.Atoi: parsing "-": invalid syntax
`

**Comment by dmachard** [comment]
can you share your config ?

**Comment by mikeS7** [comment]
Docker image for arch armv7l
Default config with modified part:

```
multiplexer:
  collectors:
    - name: pihole
      dnstap:
        listen-ip: 0.0.0.0
        listen-port: 6000

  loggers:
    - name: console
      stdout:
        mode: text
    - name: bgpRU
      dnstap:
        remote-address: 192.168.7.16
        remote-port: 6031
#   # unix socket path
        sock-path: null
#   # interval in second between retry reconnect
#   retry-interval: 5
#   # enable tls
#   tls-support: false
#   # insecure skip verify
#   tls-insecure: false

  routes:
    - from: [ pihole ]
      to: [ console, bgpRU ]
```
