### ISSUE TITLE
pcap file collector source?

### ISSUE THREAD

**Issue by danielloader** [dmachard/go-dns-collector#148]
Would it be possible to implement collecting DNS traffic from a pcap file in addition to the live sniffing of traffic?

Appreciate there's not a lot to go on here.

**Comment by dmachard** [comment]
This feature will be implemented in the next release.
The collector will watch a directory of PCAP files and ingest them if new one are detected.

**Comment by danielloader** [comment]
Quick question while you're developing it:

How will this application be able to report if a file is read successfully or not?

Say I have a script that runs to pull new files from S3 in the background and puts them in `/pcaps`, how would I go about clearing the files down after the processing is done?

**Comment by dmachard** [comment]
> Quick question while you're developing it:
> 
> How will this application be able to report if a file is read successfully or not?

Currently, the message `ingest [%s] terminated` will be printed in the standard output if debug mode is enabled.

> Say I have a script that runs to pull new files from S3 in the background and puts them in `/pcaps`, how would I go about clearing the files down after the processing is done?

The`delete-after` option will be available to delete automatically the pcap file on success processing

Ok for you ?

Below a overview of all settings for this new collector
```
pcap:
   # directory to watch for pcap files to ingest
   watch-dir: /tmp
   # filter only on source and destination port
   dns-port: 53
   # drop all queries
   drop-queries: false
   # drop all replies
   drop-replies: false
   # delete pcap file after ingest
   delete-after: false
```
