### ISSUE TITLE
Feature request: custom field boundaries / delimiters for the text-format template

### ISSUE THREAD

**Issue by MarcBrendel** [dmachard/go-dns-collector#254]
First of all: thank you for this very awesome project! It has a lot of useful features, the documentation is very well written and the software works reliably even under higher load conditions.

When using the `text` format with Loki, the `pattern` parser allows for a very straightforward extraction of labels:

`config.yml`:
```YAML
text-format: "timestamp-rfc3339ns identity operation rcode queryip queryport family protocol length qname qtype latency"
```
`LogQL`:
```
pattern "<timestamp_rfc3339ns> <identity> <operation> <rcode> <queryip> <queryport> <family> <protocol> <length> <qname> <qtype> <latency>"
```

This works fine, until the received data is somehow malformed, e.g. someone is using spaces in the `qname` field. Would it be possible to define custom delimiters in the `text-format` template? For example:

```YAML
text-format: "timestamp-rfc3339ns; identity; operation; rcode; queryip; queryport; family; protocol; length; qname; qtype; latency"

or

text-format: "timestamp-rfc3339ns identity operation rcode queryip queryport family protocol length qname qtype latency"
text-format-delimiter: ";"
```

Alternatively (or additionally) the optional configuration of quotation marks around each field would also solve this problem, for example:

```YAML
text-format: "qname qtype"
text-format-field-boundary: "
```
=> `"example.org" "A"`

```YAML
text-format: "qname qtype"
text-format-field-boundary: !
```
=> `!example.org! !A!`

Maybe both solutions can be combined inside the `text-format` option as well? For example:

```YAML
text-format: "\"qname\", \"qtype\""
```

I am not sure how difficult it would be to implement something like this, but I think it would really improve the ability to reliably parse the data in the default `text` format. Let me know what you think.
